### ISSUE TITLE
Add all the available greek tax offices (ΔΟΥ)

### ISSUE THREAD

**Issue by tsevdos** [tsevdos/elUtils#29]
First let's identify / collect all the data, and as a second phase we can start creating various utility methods (ex. in GeoUtils).

**Comment by DionisisChris** [comment]
Found from https://aade.gr/epikoinonia/plirofories-doy

Here is the excel containing all the required info.

[euretirio_xorikis.xlsx](https://github.com/tsevdos/elUtils/files/14424528/euretirio_xorikis.xlsx)

**Comment by DionisisChris** [comment]
Initial aggregation of the data from euretio_xorikis.xlsx(above) is done and can be found in the attached JSON. 
The aggregation has been made in a tree style as shown in the diagram bellow.
![Image](https://github.com/tsevdos/elUtils/assets/61205925/f38638d4-a132-4d36-bfdd-988eb036241c)
Still pending the mapping of the data with the existing types.

Please for you feedback :)
[test.json](https://github.com/tsevdos/elUtils/files/14528940/test.json)

**Comment by DionisisChris** [comment]
Adding the Json with the mapping.
[taxOffices-el.json](https://github.com/tsevdos/elUtils/files/14554802/taxOffices-el.json)

The structure that I used is the following.
`export type TaxOffice = {
  id: number;
  name: string;
  unit: Unit[];
};`

**Comment by tsevdos** [comment]
fixed with https://github.com/tsevdos/elUtils/pull/76
