### ISSUE TITLE
Create a formatUtils module and add the formatWeight function

### ISSUE THREAD

**Issue by raptisj** [tsevdos/elUtils#66]
I’m going forward with an implementation of the formatWeight util, a follow-up from [this](https://github.com/tsevdos/elUtils/discussions/52) discussion

@tsevdos Can you assign me to this issue and link it to the roadmap project?

**Comment by tsevdos** [comment]
Please create a new `formatUtils.ts` module 😁 

We need it for all the upcoming format utilities (https://github.com/tsevdos/elUtils/issues/42, https://github.com/tsevdos/elUtils/issues/43, https://github.com/tsevdos/elUtils/issues/44, etc. )

**Comment by tsevdos** [comment]
Closed with https://github.com/tsevdos/elUtils/pull/67
